name:                multpuzzle
version:             0.1.0.0
github:              "githubuser/multpuzzle"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/multpuzzle#readme>

dependencies:
- base >= 4.7 && < 5
- brick >= 0.47
- containers >= 0.6.0.1 && < 0.7
- MonadRandom >= 0.5.1.1
- random-shuffle >= 0.0.4

library:
  source-dirs: src

executables:
  multpuzzle-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - multpuzzle

tests:
  multpuzzle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - multpuzzle
